DROP TABLE IF EXISTS ADMINS;
CREATE TABLE ADMINS (
	adminId 	int AUTO_INCREMENT,
	name 		VARCHAR(255) NOT NULL,
	password 	VARCHAR(255) NOT NULL,
	PRIMARY KEY (adminId)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DOCTORS;
CREATE TABLE DOCTORS (
	doctorId 	int AUTO_INCREMENT,
	firstName 	VARCHAR(255) NOT NULL,
	secondName 	VARCHAR(255),
	lastName 	VARCHAR(255) NOT NULL,
	password 	VARCHAR(255) NOT NULL,
	PRIMARY KEY (doctorId)
) DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS PATIENTS;
CREATE TABLE PATIENTS (
	patientId 	int AUTO_INCREMENT,
	firstName 	VARCHAR(255) NOT NULL,
	secondName 	VARCHAR(255),
	lastName 	VARCHAR(255) NOT NULL,
	birthday 	DATE NOT NULL,
	PRIMARY KEY (patientId)
) DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS DIAGNOSES;
CREATE TABLE DIAGNOSES (
	diagnosisId 	int AUTO_INCREMENT,
	consultDate 	DATE NOT NULL,
	result 			VARCHAR(10) NOT NULL,
	patientId 		int NOT NULL, 
	CONSTRAINT check_result CHECK (result IN ('SANATOS', 'BOLNAV', 'NECUNOSCUT')),
	PRIMARY 	KEY (diagnosisId),
	FOREIGN KEY (patientId) REFERENCES PATIENTS(patientId) 
		ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARSET=utf8;
