/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cemadoare.gui;

import cemadoare.logger.MyLogger;
import cemadoare.service.FileSaver;
import cemadoare.service.MatlabFunctionCaller;
import cemadoare.util.Constants;
import org.apache.log4j.Logger;

/**
 * @author Filip
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents(); otherNeedfulStuff();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataContentSelectionButtonGroup = new javax.swing.ButtonGroup();
        backgroundPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        classificationTextPane = new javax.swing.JTextPane();
        importButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        consoleTextPane = new javax.swing.JTextPane();
        importLabel = new javax.swing.JLabel();
        arrhythmiaRButton = new javax.swing.JRadioButton();
        stenosisRButton = new javax.swing.JRadioButton();
        dataSetLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        dataSetLabel1 = new javax.swing.JLabel();
        trainButton = new javax.swing.JButton();
        classifyButton = new javax.swing.JButton();
        dataSetLabel2 = new javax.swing.JLabel();
        dataSetLabel3 = new javax.swing.JLabel();
        consoleLabel = new javax.swing.JLabel();
        classificationLabel = new javax.swing.JLabel();
        adminPicture = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CeMaDoare - Inerfata Admin");
        setMinimumSize(new java.awt.Dimension(600, 500));
        setSize(new java.awt.Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setMinimumSize(new java.awt.Dimension(600, 500));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(600, 500));

        classificationTextPane.setEditable(false);
        jScrollPane1.setViewportView(classificationTextPane);

        importButton.setText("Import");
        importButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importButtonActionPerformed(evt);
            }
        });

        consoleTextPane.setEditable(false);
        jScrollPane3.setViewportView(consoleTextPane);

        importLabel.setText("Import .mat file");

        dataContentSelectionButtonGroup.add(arrhythmiaRButton);
        arrhythmiaRButton.setText("Arrhythmia");
        arrhythmiaRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrhythmiaRButtonActionPerformed(evt);
            }
        });

        dataContentSelectionButtonGroup.add(stenosisRButton);
        stenosisRButton.setText("Stenosis");
        stenosisRButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stenosisRButtonActionPerformed(evt);
            }
        });

        dataSetLabel.setText("Select the content of data in .mat file ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classifier1", "Classifier2", "Classifier3", "MyClassifier" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        dataSetLabel1.setText("Select the type of classifier");

        trainButton.setText("Train");
        trainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainButtonActionPerformed(evt);
            }
        });

        classifyButton.setText("Classify");
        classifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classifyButtonActionPerformed(evt);
            }
        });

        dataSetLabel2.setText("Train the classifier");

        dataSetLabel3.setText("Start the classification");

        consoleLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        consoleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        consoleLabel.setText("Console");

        classificationLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classificationLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        classificationLabel.setText("Classification");

        adminPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/admin.png"))); // NOI18N

        welcomeLabel.setText("Welcome Filip");

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(consoleLabel)
                        .addGap(248, 248, 248)
                        .addComponent(classificationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(classifyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arrhythmiaRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(importButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataSetLabel3)
                            .addComponent(dataSetLabel2)
                            .addComponent(dataSetLabel1)
                            .addComponent(dataSetLabel)
                            .addComponent(importLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(stenosisRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(223, 223, 223)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(logOutButton))
                    .addComponent(adminPicture))
                .addGap(33, 33, 33))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPanelLayout.createSequentialGroup()
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(stenosisRButton)
                                        .addComponent(dataSetLabel))
                                    .addComponent(arrhythmiaRButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dataSetLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(trainButton)
                                    .addComponent(dataSetLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(backgroundPanelLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(importLabel)
                                    .addComponent(importButton))))
                        .addGap(13, 13, 13)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(classifyButton)
                            .addComponent(dataSetLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(backgroundPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(adminPicture)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(welcomeLabel)
                            .addComponent(logOutButton))))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(consoleLabel)
                    .addComponent(classificationLabel))
                .addGap(5, 5, 5)
                .addGroup(backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrhythmiaRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrhythmiaRButtonActionPerformed
        APP_LOGGER.logIn(consoleTextPane, "Arrhythmia data set was selected");
    }//GEN-LAST:event_arrhythmiaRButtonActionPerformed

    private void stenosisRButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stenosisRButtonActionPerformed
        APP_LOGGER.logIn(consoleTextPane, "Stenosis data set was selected");
    }//GEN-LAST:event_stenosisRButtonActionPerformed

    private void classifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classifyButtonActionPerformed
        if (isTrained) {
            APP_LOGGER.logIn(consoleTextPane, "Starting classification");
            isClassified = true;
            matlabFunctionCaller.callClassifier();
            APP_LOGGER.logIn(classificationTextPane, "Results of the classification");
        } else {
            APP_LOGGER.logErrorIn(consoleTextPane, "First we need to train the classifier", true);
        }
    }//GEN-LAST:event_classifyButtonActionPerformed

    private void importButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_importButtonActionPerformed
        String matlabDataPath = Constants.PATHS.MATLAB_DATA.getPath();
        APP_LOGGER.logIn(consoleTextPane, "Import was clicked");
        fileSaver.saveFileTo(matlabDataPath);
        APP_LOGGER.logIn(consoleTextPane, "File saved to " + matlabDataPath);
    }//GEN-LAST:event_importButtonActionPerformed

    private void trainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainButtonActionPerformed
        String selected = String.valueOf(jComboBox1.getSelectedItem());
        APP_LOGGER.logIn(consoleTextPane, selected + " is getting trained");
        // train the classifier
        isTrained = true;
        // prompt the user that training is done
    }//GEN-LAST:event_trainButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String selected = String.valueOf(jComboBox1.getSelectedItem());
        APP_LOGGER.logIn(consoleTextPane, selected + "classifier was selected");
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        setVisible(false);
        new Login().setVisible(true);
        LOGGER.info("Admin has been successfully logged off");
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void otherNeedfulStuff() {
        matlabFunctionCaller.connectToMatlablEngine();
        LOGGER.info("Created a new Matlab engine session");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminPicture;
    private javax.swing.JRadioButton arrhythmiaRButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JLabel classificationLabel;
    private javax.swing.JTextPane classificationTextPane;
    private javax.swing.JButton classifyButton;
    private javax.swing.JLabel consoleLabel;
    private javax.swing.JTextPane consoleTextPane;
    private javax.swing.ButtonGroup dataContentSelectionButtonGroup;
    private javax.swing.JLabel dataSetLabel;
    private javax.swing.JLabel dataSetLabel1;
    private javax.swing.JLabel dataSetLabel2;
    private javax.swing.JLabel dataSetLabel3;
    private javax.swing.JButton importButton;
    private javax.swing.JLabel importLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JRadioButton stenosisRButton;
    private javax.swing.JButton trainButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables

    private final static Logger LOGGER = Logger.getLogger(Admin.class);

    private final MatlabFunctionCaller matlabFunctionCaller = MatlabFunctionCaller.getInstance();
    private final FileSaver fileSaver = new FileSaver(this);
    private final MyLogger APP_LOGGER = MyLogger.getInstance();

    private boolean isTrained;
    private boolean isClassified;
}
